[project]
name = "code-p10"
version = "0.1.0"
description = ""
authors = [
    {name = "Nels-j"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.6,<7.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)"
]

[dependency-groups]
dev = [
    "django-debug-toolbar (>=7.0.0,<8.0.0)",
    "ruff (>=0.15.20,<0.16.0)",
    "mypy (>=2.1.0,<3.0.0)",
    "django-stubs (>=6.0.6,<7.0.0)",
    "djangorestframework-stubs (>=3.17.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
