# Generated by Django 6.0.7 on 2026-08-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_comment_issue_remove_contributor_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_archived',
        ),
    ]
