// https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
// Variables en provenance soit de http-client.env.json, soit de http-client.private.env

### Login
POST {{host}}/auth/jwt/create/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    // Stockage des tokens dans les variables globales pour les utiliser dans les requêtes suivantes
    client.global.set("access_token", response.body.access);
    client.global.set("refresh_token", response.body.refresh);
%}

### Refresh token
POST {{host}}/auth/jwt/refresh/
Content-Type: application/json

{
  "refresh": "{{refresh_token}}"
}

> {%
    // Mise à jour du token d'accès dans les variables globales pour les utiliser dans les requêtes suivantes
    client.global.set("access_token", response.body.access);
%}
