// https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
// Variables en provenance soit de http-client.env.json, soit de http-client.private.env

### Login
POST {{host}}/auth/jwt/create/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    // Stockage des tokens dans les variables globales pour les utiliser dans les requêtes suivantes
    client.global.set("access_token", response.body.access);
    client.global.set("refresh_token", response.body.refresh);
%}

### User list reachable with authentication
GET {{host}}/users/
Authorization: Bearer {{access_token}}

> {%
    client.log("Accès à l'endpoint /users/ OK si le token fourni est valide.");
    client.log("Liste des utilisateurs : " + JSON.stringify(response.body, null, 2));
%}

### Create a new user
POST {{host}}/users/
Content-Type: application/json

{
  "username": "jeuditreizeaout_1",
  "password": "ApiPa55word",
  "birth_date": "1977-01-01",
  "can_be_contacted": true
}

### retrieve me
GET {{host}}/users/me/
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Update me
PATCH {{host}}/users/12/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "can_be_contacted": true,
  "can_data_be_shared": false
}